### ISSUE TITLE
Adding GPUs to jobs without `remote`

### ISSUE THREAD

**Issue by aittalam** [mozilla-ai/lm-buddy#50]
Jobs which do not rely on `ray.remote`, such as `lm-harness`, run without GPUs by default.

If we want to add GPUs to our jobs, we need to manually add gpus to `ray.submit` (see [here](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/sdk.html#specifying-cpu-and-gpu-resources)), for instance when it is called in the example notebooks.

This is ok, I just wanted to raise this to make sure we describe this behavior in the documentation. The reason is that `lm-harness` jobs break if e.g. we run an evaluation on a quantized model without using a GPU.

**Comment by veekaybee** [comment]
Just got this issue as well replicating a run from scratch, will open a ticket for it

**Comment by veekaybee** [comment]
Resolved with the above PR ^
